In [12]:
import torch
from datasets import Dataset

In [2]:
t = torch.zeros(4,4)

In [15]:
ds = Dataset(data = {"labels":[1,2,3,4,5], "features":[1,2,3,4,5]})

TypeError: Dataset.__init__() got an unexpected keyword argument 'data'

In [81]:
metrics = {
    "type": {
        "f1": {"compute": True, "method": ["micro", "macro", "weighted"]},
        "recall": {"compute": True, "method": ["micro", "macro", "weighted"]},
        "MulticlassAccuracy": {"compute": True, "method": ["micro", "macro", "None"]},
        "precision":{"compute": True, "method": ["micro", "macro", "weighted"]}
        
    },
    "optimize": {"name": "f1 micro"}
}

metrics = {metric: details["method"] for metric, details in metrics["type"].items() if details["compute"]}


In [82]:
metrics

{'f1': ['micro', 'macro', 'weighted'],
 'recall': ['micro', 'macro', 'weighted'],
 'MulticlassAccuracy': ['micro', 'macro', 'None'],
 'precision': ['micro', 'macro', 'weighted']}

In [84]:
from transformers import EvalPrediction
from torcheval.metrics import MulticlassAccuracy
from sklearn.metrics import f1_score, recall_score, precision_score
master_metric_mapper = {
    "f1_micro": f1_score, # SKLEARN METRIC
    "f1_macro": f1_score,
    "f1_weighted": f1_score,
    "f1_binary": f1_score,
    "MulticlassAccuracy_micro" : MulticlassAccuracy(average = 'micro', num_classes =  4, k = 1) ,# TORCH METRIC
    "MulticlassAccuracy_macro" : MulticlassAccuracy(average = 'macro', num_classes = 4, k = 1) ,# TORCH METRIC
    "MulticlassAccuracy_None" : MulticlassAccuracy(average = None, num_classes =  4, k = 1) ,# TORCH METRIC
    "recall_micro":recall_score,# SKLEARN METRIC
    "recall_macro":recall_score,
    "recall_weighted":recall_score,
    "recall_binary":recall_score,
    "precision_micro":precision_score,# SKLEARN METRIC
    "precision_macro":precision_score,
    "precision_weighted":precision_score,
    "precision_binary":precision_score
}

_metric_obj = {}
for metric,methods in metrics.items():
    for method in methods:
        key_name = metric + "_" + method
        print(key_name)
        metric_obj = master_metric_mapper.get(key_name, None)
        if metric_obj is not None:
            _metric_obj[key_name] = metric_obj

f1_micro
f1_macro
f1_weighted
recall_micro
recall_macro
recall_weighted
MulticlassAccuracy_micro
MulticlassAccuracy_macro
MulticlassAccuracy_None
precision_micro
precision_macro
precision_weighted


In [85]:
_metric_obj

{'f1_micro': <function sklearn.metrics._classification.f1_score(y_true, y_pred, *, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn')>,
 'f1_macro': <function sklearn.metrics._classification.f1_score(y_true, y_pred, *, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn')>,
 'f1_weighted': <function sklearn.metrics._classification.f1_score(y_true, y_pred, *, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn')>,
 'recall_micro': <function sklearn.metrics._classification.recall_score(y_true, y_pred, *, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn')>,
 'recall_macro': <function sklearn.metrics._classification.recall_score(y_true, y_pred, *, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn')>,
 'recall_weighted': <function sklearn.metrics._classification.recall_score(y_true, y_pred, *, labels=None, pos_label=1, averag

In [93]:
import numpy as np
y_true =torch.tensor([[0.2,0.2,0.9,0.8],
                      [0.9,0.2,0.2,0.8],
                      [0.2,0.2,0.9,0.8],
                      [0.9,0.2,0.2,0.8]
                      ])
y_true_label =torch.argmax(y_true, dim=1)
print(y_true_label)
y_pred =torch.tensor([[0.1,0.1,0.1,0.6],
                      [0.9,0.3,0.3,0.3],
                      [0.3,0.3,0.1,0.1],
                      [0.9,0.1,0.3,0.1]
                      ])
y_pred_class = torch.argmax(y_pred, dim=1)
print(y_pred_class)
print(_metric_obj["f1_micro"](y_true = y_true_label,y_pred = y_pred_class , average="micro"))
print(_metric_obj["f1_macro"](y_true = y_true_label,y_pred = y_pred_class , average="macro"))
print(_metric_obj["f1_weighted"](y_true = y_true_label,y_pred = y_pred_class , average="weighted"))
print(_metric_obj["recall_micro"](y_true = y_true_label,y_pred = y_pred_class , average="micro"))
print(_metric_obj["recall_macro"](y_true = y_true_label,y_pred = y_pred_class , average="macro"))
print(_metric_obj["recall_weighted"](y_true = y_true_label,y_pred = y_pred_class , average="weighted"))
print(_metric_obj["precision_micro"](y_true = y_true_label,y_pred = y_pred_class , average="micro"))
print(_metric_obj["precision_macro"](y_true = y_true_label,y_pred = y_pred_class , average="macro"))
print(_metric_obj["precision_weighted"](y_true = y_true_label,y_pred = y_pred_class , average="weighted"))

_metric_obj["MulticlassAccuracy_micro"].update(input =y_pred_class, target = y_true_label)
_metric_obj["MulticlassAccuracy_macro"].update(input =y_pred, target = y_true_label)
_metric_obj["MulticlassAccuracy_None"].update(input =y_pred, target = y_true_label)
print(_metric_obj["MulticlassAccuracy_micro"].compute())
print(_metric_obj["MulticlassAccuracy_macro"].compute())
print(_metric_obj["MulticlassAccuracy_None"].compute())

tensor([2, 0, 2, 0])
tensor([3, 0, 2, 1])
0.5
0.3333333333333333
0.6666666666666666
0.5
0.25
0.5
0.5
0.5
1.0
tensor(0.5000)
tensor(0.5000)
tensor([0.5000,    nan, 0.5000,    nan])


c:\Users\Jorge\Desktop\MASTER_IA\TFM\proyectoCHROMADB\env\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Jorge\Desktop\MASTER_IA\TFM\proyectoCHROMADB\env\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [92]:
_metric_obj["MulticlassAccuracy_micro"].reset()
_metric_obj["MulticlassAccuracy_macro"].reset()
_metric_obj["MulticlassAccuracy_None"].reset()

In [67]:
t3.shape

torch.Size([8, 2])

In [8]:
t4 = t.unsqueeze(1)

In [9]:
t4.shape

torch.Size([4, 1, 4])

In [11]:
t[0,3].item()

0.0