In [1]:
import torch
from datasets import Dataset

c:\Users\Jorge\Desktop\MASTER_IA\TFM\proyectoCHROMADB\env\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")
print(f"CUDA version: {torch.version.cuda}")
print(f"Device name: {torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'CPU'}")
print(torch.cuda.get_arch_list())


PyTorch version: 2.3.0+cu118
CUDA available: True
CUDA version: 11.8
Device name: NVIDIA RTX A500 Laptop GPU


In [3]:
print(torch.cuda.get_arch_list())

['sm_37', 'sm_50', 'sm_60', 'sm_61', 'sm_70', 'sm_75', 'sm_80', 'sm_86', 'sm_90', 'compute_37']


In [4]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

cuda


In [5]:
t = torch.zeros(1)

In [6]:
t.to(device)

tensor([0.], device='cuda:0')

In [81]:
metrics = {
    "type": {
        "f1": {"compute": True, "method": ["micro", "macro", "weighted"]},
        "recall": {"compute": True, "method": ["micro", "macro", "weighted"]},
        "MulticlassAccuracy": {"compute": True, "method": ["micro", "macro", "None"]},
        "precision":{"compute": True, "method": ["micro", "macro", "weighted"]}
        
    },
    "optimize": {"name": "f1 micro"}
}

metrics = {metric: details["method"] for metric, details in metrics["type"].items() if details["compute"]}


In [82]:
metrics

{'f1': ['micro', 'macro', 'weighted'],
 'recall': ['micro', 'macro', 'weighted'],
 'MulticlassAccuracy': ['micro', 'macro', 'None'],
 'precision': ['micro', 'macro', 'weighted']}

In [84]:
from transformers import EvalPrediction
from torcheval.metrics import MulticlassAccuracy
from sklearn.metrics import f1_score, recall_score, precision_score
master_metric_mapper = {
    "f1_micro": f1_score, # SKLEARN METRIC
    "f1_macro": f1_score,
    "f1_weighted": f1_score,
    "f1_binary": f1_score,
    "MulticlassAccuracy_micro" : MulticlassAccuracy(average = 'micro', num_classes =  4, k = 1) ,# TORCH METRIC
    "MulticlassAccuracy_macro" : MulticlassAccuracy(average = 'macro', num_classes = 4, k = 1) ,# TORCH METRIC
    "MulticlassAccuracy_None" : MulticlassAccuracy(average = None, num_classes =  4, k = 1) ,# TORCH METRIC
    "recall_micro":recall_score,# SKLEARN METRIC
    "recall_macro":recall_score,
    "recall_weighted":recall_score,
    "recall_binary":recall_score,
    "precision_micro":precision_score,# SKLEARN METRIC
    "precision_macro":precision_score,
    "precision_weighted":precision_score,
    "precision_binary":precision_score
}

_metric_obj = {}
for metric,methods in metrics.items():
    for method in methods:
        key_name = metric + "_" + method
        print(key_name)
        metric_obj = master_metric_mapper.get(key_name, None)
        if metric_obj is not None:
            _metric_obj[key_name] = metric_obj

f1_micro
f1_macro
f1_weighted
recall_micro
recall_macro
recall_weighted
MulticlassAccuracy_micro
MulticlassAccuracy_macro
MulticlassAccuracy_None
precision_micro
precision_macro
precision_weighted


In [85]:
_metric_obj

{'f1_micro': <function sklearn.metrics._classification.f1_score(y_true, y_pred, *, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn')>,
 'f1_macro': <function sklearn.metrics._classification.f1_score(y_true, y_pred, *, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn')>,
 'f1_weighted': <function sklearn.metrics._classification.f1_score(y_true, y_pred, *, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn')>,
 'recall_micro': <function sklearn.metrics._classification.recall_score(y_true, y_pred, *, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn')>,
 'recall_macro': <function sklearn.metrics._classification.recall_score(y_true, y_pred, *, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn')>,
 'recall_weighted': <function sklearn.metrics._classification.recall_score(y_true, y_pred, *, labels=None, pos_label=1, averag

In [97]:
import numpy as np
y_true =torch.tensor([[0.2,0.9,0.9,0.8],
                      [0.9,0.2,0.2,0.8],
                      [0.2,0.2,0.9,0.8],
                      [0.9,0.2,0.2,0.8]
                      ])
y_true_label =torch.argmax(y_true, dim=1)
print(y_true_label)
y_pred =torch.tensor([[0.1,0.1,0.1,0.6],
                      [0.9,0.3,0.3,0.3],
                      [0.3,0.3,0.1,0.1],
                      [0.9,0.1,0.3,0.1]
                      ])
y_pred_class = torch.argmax(y_pred, dim=1)
print(y_pred_class)
print(_metric_obj["f1_micro"](y_true = y_true_label,y_pred = y_pred_class , average="micro"))
print(_metric_obj["f1_macro"](y_true = y_true_label,y_pred = y_pred_class , average="macro"))
print(_metric_obj["f1_weighted"](y_true = y_true_label,y_pred = y_pred_class , average="weighted"))
print(_metric_obj["recall_micro"](y_true = y_true_label,y_pred = y_pred_class , average="micro"))
print(_metric_obj["recall_macro"](y_true = y_true_label,y_pred = y_pred_class , average="macro"))
print(_metric_obj["recall_weighted"](y_true = y_true_label,y_pred = y_pred_class , average="weighted"))
print(_metric_obj["precision_micro"](y_true = y_true_label,y_pred = y_pred_class , average="micro"))
print(_metric_obj["precision_macro"](y_true = y_true_label,y_pred = y_pred_class , average="macro"))
print(_metric_obj["precision_weighted"](y_true = y_true_label,y_pred = y_pred_class , average="weighted"))

_metric_obj["MulticlassAccuracy_micro"].update(input =y_pred_class, target = y_true_label)
_metric_obj["MulticlassAccuracy_macro"].update(input =y_pred, target = y_true_label)
_metric_obj["MulticlassAccuracy_None"].update(input =y_pred, target = y_true_label)
print(_metric_obj["MulticlassAccuracy_micro"].compute())
print(_metric_obj["MulticlassAccuracy_macro"].compute())
print(_metric_obj["MulticlassAccuracy_None"].compute())

tensor([1, 0, 2, 0])
tensor([3, 0, 0, 0])
0.5
0.2
0.4
0.5
0.25
0.5
0.5
0.16666666666666666
0.3333333333333333
tensor(0.5000)
tensor(0.3333)
tensor([1., 0., 0., nan])


c:\Users\Jorge\Desktop\MASTER_IA\TFM\proyectoCHROMADB\env\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Jorge\Desktop\MASTER_IA\TFM\proyectoCHROMADB\env\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Jorge\Desktop\MASTER_IA\TFM\proyectoCHROMADB\env\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier,

In [ ]:
class BoeNetVanilla(nn.Module):
    def __init__(self, d_model :int , boe_labels : int) -> None:
       super().__init__()
       self.d_model = d_model # (384)
       self.boe_labels = boe_labels # (?)
       
       # Arquitecture 
       # (batch, 384)
       self.l_1 = nn.Linear(in_features= self.d_model, out_features = 700, bias = True)
       self.tan_h = nn.Tanh()
       self.drop_1 = nn.Dropout(p = 0.2)
       self.l_2 = nn.Linear(in_features= 700, out_features = 1200, bias = True)
       self.Relu = nn.ReLU()
       self.drop_2 = nn.Dropout(p = 0.3)
       # (batch, 10)
       self.l_3 = nn.Linear(in_features=  1200 , out_features = self.boe_labels, bias = True)
       
    def forward(self,x):
        h = self.drop_1(self.tan_h(self.l_1(x)))
        h = self.drop_2(self.Relu(self.l_2(h)))
        return self.l_3(h)
    
    @staticmethod
    def LossFactory():
        return nn.CrossEntropyLoss()
    
    @staticmethod
    def OptimizerFactory(model, lr : float = 0.001 , betas : tuple = (0.9, 0.999), eps: float =1e-08):
        return torch.optim.Adam(model.parameters(), lr=lr, betas=betas, eps=

In [98]:
_metric_obj["MulticlassAccuracy_micro"].reset()
_metric_obj["MulticlassAccuracy_macro"].reset()
_metric_obj["MulticlassAccuracy_None"].reset()

In [1]:
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(device)

NameError: name 'torch' is not defined

In [8]:
t4 = t.unsqueeze(1)

In [9]:
t4.shape

torch.Size([4, 1, 4])

In [11]:
t[0,3].item()

0.0